fix test carryover with MainHelper
console.error would print after this test would run due to some Promises
never finishing.

This fixes the following stacktrace:
MainHelper Tests
    ✓ getCurrentNotificationType for default permission (84 ms)

  console.error
    TypeError: Cannot read property '_location' of null
        at Window.get location [as location] (/sdk/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:376:79)
        at Function.getWindowEnv (/sdk/src/shared/managers/SdkEnvironment.ts:203:13)
        at Database.getWindowEnv [as shouldUsePostmam] (/sdk/src/shared/services/Database.ts:99:27)
        at Database.shouldUsePostmam [as getAll] (/sdk/src/shared/services/Database.ts:131:14)
        at Function.getAll (/sdk/src/shared/services/Database.ts:638:45)
        at ModelCache.getAll [as getCachedEncodedModels] (/sdk/src/core/caching/ModelCache.ts:106:27)
        at ModelCache.getCachedEncodedModels [as getAndDecodeModelsWithModelName] (/sdk/src/core/caching/ModelCache.ts:115:31)
        at ModelCache.getAndDecodeModelsWithModelName [as load] (/sdk/src/core/caching/ModelCache.ts:76:41)
        at runNextTicks (internal/process/task_queues.js:60:5)
        at processImmediate (internal/timers.js:437:9)

      30 |       }
      31 |     ).catch(e => {
    > 32 |       Log.error(e);
         |           ^
      33 |     });
      34 |   }
      35 |

      at error (src/core/CoreModule.ts:32:11)